SIM = verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../../rtl/bs_accelerator.sv
TOPLEVEL = bs_accelerator
MODULE = test_bs_accelerator
EXTRA_ARGS += --sv --trace

include $(shell cocotb-config --makefiles)/Makefile.sim