SIM = verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../../rtl/parser.sv
TOPLEVEL = parser
MODULE = test_parser
EXTRA_ARGS += --sv --trace

include $(shell cocotb-config --makefiles)/Makefile.sim